SITE_URL = 'http://127.0.0.1:5000'
DATABASE = '/tmp/FRAPI.db'
DEBUG = True
SECRET_KEY = '\xeb\xd6T\xc6/\x12Q&j\xaa8\x0f**\xb4\x0b/\xa7\xad~\xe3\x89`\x96'
FR_DIR = {'training': 'training', 'testing': 'testing'}
UPLOAD_DIR = {'training': 'uploads/training', 'testing': 'uploads/testing'}
ALLOWED_EXTENSIONS = set(['png', 'jpg', 'jpeg'])
BACKUP_INTERVAL = 5
MODEL_BACKUP_NAME = 'ModelBackUp.xml'
APP_DATA_BACKUP_NAME = 'data.pkl'
CONFIDENCE_THRESHOLD = 70
